name: Daily Commit Bot

on:
  schedule:
    - cron: "30 0 * * *"  # 6:00 AM IST
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Make Daily Commit
        run: |
          echo "Last run: $(date)" >> daily.txt
          git config --global user.name "Akshad Bot"
          git config --global user.email "akshad@users.noreply.github.com"
          git add .
          git commit -m "Daily automated commit"
          git push
